// Generated by 'unplugin-auto-import'
export {}
declare global {
  const ServerEnv: typeof import('../config/enums')['ServerEnv']
  const StorageKey: typeof import('../config/enums')['StorageKey']
  const acceptHMRUpdate: typeof import('pinia')['acceptHMRUpdate']
  const createPinia: typeof import('pinia')['createPinia']
  const defineStore: typeof import('pinia')['defineStore']
  const getActivePinia: typeof import('pinia')['getActivePinia']
  const mapActions: typeof import('pinia')['mapActions']
  const mapGetters: typeof import('pinia')['mapGetters']
  const mapState: typeof import('pinia')['mapState']
  const mapStores: typeof import('pinia')['mapStores']
  const mapWritableState: typeof import('pinia')['mapWritableState']
  const request: typeof import('../utils/request')['request']
  const setActivePinia: typeof import('pinia')['setActivePinia']
  const setMapStoreSuffix: typeof import('pinia')['setMapStoreSuffix']
  const storeToRefs: typeof import('pinia')['storeToRefs']
  const useAppStore: typeof import('../store/app')['useAppStore']
  const useUserStore: typeof import('../store/user')['useUserStore']
  const verifyPhone: typeof import('../utils/commons')['verifyPhone']
}
